name: CI
on: [push, pull_request]

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install packages - Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --ignore-scripts
        shell: bash
      # - name: Create local node and deploy
      #   run: |
      #     yarn hardhat node &
      #     yarn hardhat run scripts/deploy.ts --network localhost
      - name: Run Tests
        run: yarn run test:gas